#!/usr/bin/env python3
"""
extract.py — 从 SingleFile 保存的 Framer 项目页 HTML 中提取媒体和文本。

SingleFile 把图片/视频以 base64 data URI 内嵌进 HTML，本脚本用正则把它们
扫出来，按出现顺序解码保存到 assets/<slug>/，然后生成 projects.js。

用法：cd portfolio-demo && python3 scripts/extract.py
"""
import os, re, json, base64, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOWNLOADS = Path.home() / 'Downloads'
ASSETS = ROOT / 'assets'

SOURCES = [
    ('xiaohongshu', 'Xiaohongshu', 'Xiaohongshu (2026_4_19 22：13：07).html'),
    ('mokee',       'Mokee',       'Mokee (2026_4_19 22：12：38).html'),
    ('newtap',      'NewTap',      'NewTap (2026_4_19 22：12：23).html'),
    ('douyin',      'Douyin',      'Douyin (2026_4_19 22：12：05).html'),
    ('sia-tv',      'Sia TV',      'Sia-Tv (2026_4_19 22：11：43).html'),
    ('oppo',        'OPPO',        'oppo (2026_4_19 22：11：27).html'),
]

MIN_BYTES = 6000  # < 6KB 视为 favicon / 装饰，丢弃

EXT_MAP = {
    'jpeg': '.jpg', 'jpg': '.jpg', 'png': '.png', 'webp': '.webp',
    'avif': '.avif', 'gif': '.gif', 'svg': '.svg',
    'mp4': '.mp4', 'webm': '.webm', 'quicktime': '.mov',
}

# 匹配 data:image/xxx;base64,XXXX 或 data:video/xxx;base64,XXXX
DATA_URI_RE = re.compile(
    r'data:(image|video)/([a-zA-Z0-9+.-]+);base64,([A-Za-z0-9+/=]+)'
)
TITLE_RE = re.compile(r'<title[^>]*>(.*?)</title>', re.S | re.I)
TEXT_RE = re.compile(r'<(?:p|h[1-3])[^>]*>(.*?)</(?:p|h[1-3])>', re.S | re.I)
TAG_STRIP = re.compile(r'<[^>]+>')


def clean_text(s):
    s = TAG_STRIP.sub(' ', s)
    s = re.sub(r'&nbsp;|&#160;', ' ', s)
    s = re.sub(r'&amp;', '&', s)
    s = re.sub(r'&lt;', '<', s)
    s = re.sub(r'&gt;', '>', s)
    s = re.sub(r'&quot;', '"', s)
    s = re.sub(r'&#(\d+);', lambda m: chr(int(m.group(1))), s)
    s = re.sub(r'\s+', ' ', s).strip()
    return s


def process(slug, name, html_file):
    src = DOWNLOADS / html_file
    if not src.exists():
        print(f'  ! missing: {src}')
        return None
    print(f'\n→ {slug}  ({src.name})')
    raw = src.read_text(encoding='utf-8', errors='ignore')

    # 1) 提取所有 base64 媒体
    out_dir = ASSETS / slug
    out_dir.mkdir(parents=True, exist_ok=True)
    # 清空旧资源
    for f in out_dir.iterdir():
        if f.is_file():
            f.unlink()

    media = []
    seen_hash = set()
    for m in DATA_URI_RE.finditer(raw):
        kind, fmt, b64 = m.group(1), m.group(2).lower(), m.group(3)
        try:
            data = base64.b64decode(b64, validate=False)
        except Exception:
            continue
        if len(data) < MIN_BYTES:
            continue
        h = hash(data[:512]) ^ len(data)
        if h in seen_hash:
            continue
        seen_hash.add(h)
        ext = EXT_MAP.get(fmt, '.' + fmt)
        idx = len(media) + 1
        fname = f'{idx:02d}{ext}'
        (out_dir / fname).write_bytes(data)
        media.append({'type': kind, 'local': f'assets/{slug}/{fname}', 'size': len(data)})
        sys.stdout.write('.'); sys.stdout.flush()
    print(f' → {len(media)} media files saved')

    # 2) 提取文本（只取 p/h1-3，过滤太短或太长）
    texts = []
    seen_t = set()
    for m in TEXT_RE.finditer(raw):
        t = clean_text(m.group(1))
        if 20 < len(t) < 500 and t not in seen_t:
            seen_t.add(t)
            texts.append(t)

    title_match = TITLE_RE.search(raw)
    page_title = clean_text(title_match.group(1)) if title_match else name

    print(f'  {len(texts)} text blocks, title="{page_title[:60]}"')

    # 3) 组装 sections
    sections = []
    hero = media[0] if media else None
    sections.append({
        'type': 'hero',
        'title': name,
        'subtitle': texts[0] if texts else 'UX Design',
        'media': {'type': hero['type'], 'src': hero['local']} if hero else None,
    })
    if len(texts) > 1:
        sections.append({
            'type': 'text', 'eyebrow': 'OVERVIEW',
            'title': 'About', 'body': texts[1],
        })

    text_i = 2
    for m in media[1:]:
        if m['type'] == 'video':
            sections.append({
                'type': 'video', 'src': m['local'],
                'autoplay': True, 'loop': True, 'muted': True,
            })
        else:
            sections.append({'type': 'image', 'src': m['local']})
        # 每隔几张图穿插一段文本
        if text_i < len(texts) and (text_i - 2) % 3 == 0:
            sections.append({'type': 'text', 'body': texts[text_i]})
            text_i += 1

    return sections


def main():
    all_data = {}
    for slug, name, fname in SOURCES:
        try:
            sections = process(slug, name, fname)
            if sections:
                sections = [{k: v for k, v in s.items() if v is not None} for s in sections]
                all_data[slug] = {'name': name, 'sections': sections}
        except Exception as e:
            print(f'  ! {slug} failed: {e}')

    out = (
        '/* AUTO-GENERATED by scripts/extract.py — DO NOT EDIT.\n'
        '   手动定制请改 projects.js（会覆盖这里的同 slug 字段）。 */\n'
        'window.PROJECT_DATA_GENERATED = '
        + json.dumps(all_data, indent=2, ensure_ascii=False) + ';\n'
    )
    (ROOT / 'projects.generated.js').write_text(out, encoding='utf-8')
    print(f'\n✓ Wrote projects.generated.js ({len(all_data)} projects)')


if __name__ == '__main__':
    main()
